apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gluster-fast
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-fast
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
