apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fast
  annotations:
    volume.beta.kubernetes.io/storage-class: fast-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
