kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gluster-slow
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi-storage.apps.ose3sandbox.com"
  restuser: "admin"
  secretName: "heketi-secret"
  secretNamespace: "default"
