apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-slow
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
