apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gluster-slow
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-slow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
